### ISSUE TITLE
Není implementována úprava parametrů modifikátoru z scad kódu

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/processor3D#3]
Podle #1 by mělo být možné upravit nastavení modifikátoru přímo z kódu bez nutnosti vytvářet vlastní .ini soubor. Celé by to mělo fungovat tak, že u modifikátoru bude deklarátor 

```
@set_slicing_parameter(<parametr>, <hodnota>)
```

Který určí parametr a jeho hodnotu, která bude následně zapsána do AMF.

Zatím je vyřešeno používání ini souborů pro nastavování parametrů modelu/modifikátoru. Tyto parametry ze souboru jsou uloženy do python dictionary. Po té, co bude zavolána metoda nastavující jeden parametr slic3eru, tak by měla být uložena (přepsána) do toho samého objektu. Tento dictionary je následně přepsán do AMF souboru k daném objektu.

**Comment by JanKott** [comment]
S @roman-dvorak jsem procházel workflow a vytvořil jsem bash script, který řeší sloučení AMF souboru s jeho modifikátory.
Později jsem to trochu rozšířil a použil tady:
https://github.com/mlab-modules/WINDGAUGE03/blob/WINDGAUGE03A/cad/merge_modifiers.sh

Mělo by to fungovat tak, že zavolám skript s parametry file.scad (soubor ze kterého AMF vychází) a file.amf (samotné AMF) a na základě toho se složí AMF i s modifikátory.

Tenhle skript volám přímo v Makefile:
```
MERGE_APP = ./merge_modifiers.sh
...
$(AMF_DIR)/%.amf : $(SRC_DIR)/%.scad
...
    # Add modifiers to AMF files.
    $(MERGE_APP) -v -a $@ -s $<
```

Je to použitelné?

**Comment by kaklik** [comment]
Jestli je to použitelné závisí na tom, jestli tahle věc umí do toho AMF přidat k těm modifikátorům i parametry. Tj. aby nemusel existovat zvláštní ini soubor k tomu složenému AMF.

**Comment by JanKott** [comment]
V tom skriptu to je.
Mělo by to stáhnout base parametry, base konifigurák (ini), parametry modifikátorů a jejich konfiguráky a to všechno dát do jednoho AMF.
Windgauč konfiguráky nepoužívá, ale na původnim workflow příkladu to fungovalo.

**Comment by JanKott** [comment]
Čili zatim to považuju za vyřešené.
